"""API schemas package."""

from app.schemas.auth import LoginRequest, RegisterRequest, TokenResponse
from app.schemas.common import ErrorResponse, HealthResponse, ViolationRead
from app.schemas.feedback import FeedbackCreate, FeedbackRead, FeedbackSubmitResponse
from app.schemas.plan import (
    AdjustRequest,
    AdjustResponse,
    ConfirmRequest,
    ConfirmResponse,
    DailyCompletionRead,
    FeedbackAdjustmentRead,
    GoalCreate,
    GoalRead,
    InsightRead,
    PlanGenerateRequest,
    PlanGenerateResponse,
    PlanListItem,
    PlanRead,
    PreviewRead,
    PreviewResponse,
    PreviewTaskRead,
    ReplanEligibilityRead,
    ReplanRequest,
    ReplanResponse,
)
from app.schemas.task import (
    TaskRead,
    TaskStandardRead,
    TaskStandardUpdate,
    TaskUpdateRequest,
)
from app.schemas.user import UserRead, UserUpdate

__all__ = [
    "AdjustRequest",
    "AdjustResponse",
    "ConfirmRequest",
    "ConfirmResponse",
    "DailyCompletionRead",
    "ErrorResponse",
    "FeedbackAdjustmentRead",
    "FeedbackCreate",
    "FeedbackRead",
    "FeedbackSubmitResponse",
    "GoalCreate",
    "GoalRead",
    "HealthResponse",
    "InsightRead",
    "LoginRequest",
    "PlanGenerateRequest",
    "PlanGenerateResponse",
    "PlanListItem",
    "PlanRead",
    "PreviewRead",
    "PreviewResponse",
    "PreviewTaskRead",
    "RegisterRequest",
    "ReplanEligibilityRead",
    "ReplanRequest",
    "ReplanResponse",
    "TaskRead",
    "TaskStandardRead",
    "TaskStandardUpdate",
    "TaskUpdateRequest",
    "TokenResponse",
    "UserRead",
    "UserUpdate",
    "ViolationRead",
]
