"""API schemas package."""

from app.schemas.auth import LoginRequest, RegisterRequest, TokenResponse
from app.schemas.common import ErrorResponse, HealthResponse, ViolationRead
from app.schemas.feedback import FeedbackCreate, FeedbackRead, FeedbackSubmitResponse
from app.schemas.goal import GoalCreate, GoalDetailRead, GoalUpdate
from app.schemas.plan import (
    AdjustRequest,
    AdjustResponse,
    ConfirmDraftRequest,
    ConfirmResponse,
    DailyCompletionRead,
    DecomposeDay,
    DecomposeDraftTask,
    DecomposeGoal,
    DecomposeRequest,
    DecomposeResponse,
    FeedbackAdjustmentRead,
    GoalRead,
    InsightRead,
    PlanChangeDayRead,
    PlanChangeRead,
    PlanGenerateRequest,
    PlanGenerateResponse,
    PlanGoalCreate,
    PlanListItem,
    PlanRead,
    PreviewRead,
    PreviewResponse,
    PreviewTaskRead,
    ReplanEligibilityRead,
    ReplanRequest,
    ReplanResponse,
)
from app.schemas.task import (
    TaskRead,
    TaskStandardRead,
    TaskStandardUpdate,
    TaskUpdateRequest,
)
from app.schemas.user import (
    DataSufficiency,
    SchedulingPreferences,
    SituationTrendPoint,
    SituationTrendRead,
    UserRead,
    UserUpdate,
)

__all__ = [
    "AdjustRequest",
    "AdjustResponse",
    "ConfirmDraftRequest",
    "ConfirmResponse",
    "DailyCompletionRead",
    "DataSufficiency",
    "DecomposeDay",
    "DecomposeDraftTask",
    "DecomposeGoal",
    "DecomposeRequest",
    "DecomposeResponse",
    "ErrorResponse",
    "FeedbackAdjustmentRead",
    "FeedbackCreate",
    "FeedbackRead",
    "FeedbackSubmitResponse",
    "GoalCreate",
    "GoalDetailRead",
    "GoalRead",
    "GoalUpdate",
    "HealthResponse",
    "InsightRead",
    "LoginRequest",
    "PlanChangeDayRead",
    "PlanChangeRead",
    "PlanGenerateRequest",
    "PlanGenerateResponse",
    "PlanGoalCreate",
    "PlanListItem",
    "PlanRead",
    "PreviewRead",
    "PreviewResponse",
    "PreviewTaskRead",
    "RegisterRequest",
    "ReplanEligibilityRead",
    "ReplanRequest",
    "ReplanResponse",
    "SchedulingPreferences",
    "SituationTrendPoint",
    "SituationTrendRead",
    "TaskRead",
    "TaskStandardRead",
    "TaskStandardUpdate",
    "TaskUpdateRequest",
    "TokenResponse",
    "UserRead",
    "UserUpdate",
    "ViolationRead",
]
