"""initial schema

Revision ID: 4e95b02e3696
Revises: 
Create Date: 2026-09-19 03:40:02.174554+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e95b02e3696'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('execution_weight', sa.Float(), nullable=False),
    sa.Column('profile', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('goal_type', sa.Enum('long_term', 'short_term', 'project', 'habit', 'other', name='goaltype', native_enum=False, length=32), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'archived', 'cancelled', name='goalstatus', native_enum=False, length=32), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goals_user_id'), ['user_id'], unique=False)

    op.create_table('plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'superseded', 'completed', 'archived', name='planstatus', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('parent_plan_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'version', name='uq_plans_user_id_version')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plans_parent_plan_id'), ['parent_plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plans_user_id'), ['user_id'], unique=False)

    op.create_table('user_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('duration_factors', sa.JSON(), nullable=False),
    sa.Column('completion_probability', sa.JSON(), nullable=False),
    sa.Column('stress_response', sa.JSON(), nullable=False),
    sa.Column('preferred_time_slots', sa.JSON(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('completion_rate', sa.Float(), nullable=False),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('delay_reason', sa.String(length=500), nullable=True),
    sa.Column('free_text', sa.String(length=2000), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('dominant_time_of_day', sa.Enum('morning', 'afternoon', 'evening', 'night', name='timeofday', native_enum=False, length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedbacks_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedbacks_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_feedbacks_user_id_date', ['user_id', 'date'], unique=False)

    op.create_table('replan_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.Enum('manual', 'feedback_triggered', 'scheduled', 'system', name='replantriggertype', native_enum=False, length=32), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('old_version', sa.Integer(), nullable=False),
    sa.Column('new_version', sa.Integer(), nullable=False),
    sa.Column('changed_tasks', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('replan_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_replan_events_plan_id'), ['plan_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('parent_task_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=False),
    sa.Column('predicted_duration', sa.Integer(), nullable=True),
    sa.Column('cognitive_load', sa.Enum('high', 'medium', 'low', 'restorative', name='cognitiveload', native_enum=False, length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'scheduled', 'in_progress', 'completed', 'skipped', 'failed', name='taskstatus', native_enum=False, length=32), nullable=False),
    sa.Column('completion_probability', sa.Float(), nullable=True),
    sa.Column('is_flexible', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_goal_id'), ['goal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_parent_task_id'), ['parent_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index('ix_tasks_plan_id_scheduled_date', ['plan_id', 'scheduled_date'], unique=False)

    op.create_table('task_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planned_duration', sa.Integer(), nullable=False),
    sa.Column('actual_duration', sa.Integer(), nullable=True),
    sa.Column('completion_rate', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('difficulty_feedback', sa.Integer(), nullable=True),
    sa.Column('stress_before', sa.Integer(), nullable=True),
    sa.Column('stress_after', sa.Integer(), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('time_of_day', sa.Enum('morning', 'afternoon', 'evening', 'night', name='timeofday', native_enum=False, length=32), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_executions_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_executions_user_id'), ['user_id'], unique=False)

    op.create_table('task_standards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('estimated_duration', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_standards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_standards_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_standards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_standards_task_id'))

    op.drop_table('task_standards')
    with op.batch_alter_table('task_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_executions_user_id'))
        batch_op.drop_index(batch_op.f('ix_task_executions_task_id'))

    op.drop_table('task_executions')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_tasks_plan_id_scheduled_date')
        batch_op.drop_index(batch_op.f('ix_tasks_plan_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_parent_task_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_goal_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('replan_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_replan_events_plan_id'))

    op.drop_table('replan_events')
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.drop_index('ix_feedbacks_user_id_date')
        batch_op.drop_index(batch_op.f('ix_feedbacks_user_id'))
        batch_op.drop_index(batch_op.f('ix_feedbacks_plan_id'))

    op.drop_table('feedbacks')
    op.drop_table('user_models')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_user_id'))
        batch_op.drop_index(batch_op.f('ix_plans_parent_plan_id'))

    op.drop_table('plans')
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goals_user_id'))

    op.drop_table('goals')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###