"""add user profile and state tables

Revision ID: cceb72f7ccc0
Revises: 4e95b02e3696
Create Date: 2026-09-22 07:28:26.509586+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cceb72f7ccc0'
down_revision: Union[str, None] = '4e95b02e3696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mbti_type', sa.String(length=4), nullable=True),
    sa.Column('mbti_ie', sa.Float(), nullable=True),
    sa.Column('mbti_sn', sa.Float(), nullable=True),
    sa.Column('mbti_tf', sa.Float(), nullable=True),
    sa.Column('mbti_jp', sa.Float(), nullable=True),
    sa.Column('identity', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('user_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('duration_factor', sa.Float(), nullable=False),
    sa.Column('completion_prob', sa.Float(), nullable=False),
    sa.Column('stress_baseline', sa.Float(), nullable=False),
    sa.Column('energy_drain_rate', sa.Float(), nullable=False),
    sa.Column('proactive_score', sa.Float(), nullable=False),
    sa.Column('procrastination_tendency', sa.Float(), nullable=False),
    sa.Column('preferred_time_slots', sa.JSON(), nullable=False),
    sa.Column('stress_response', sa.Float(), nullable=False),
    sa.Column('state_energy', sa.Float(), nullable=False),
    sa.Column('state_fatigue', sa.Float(), nullable=False),
    sa.Column('self_efficacy', sa.Float(), nullable=False),
    sa.Column('update_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_states_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_states_user_id'))

    op.drop_table('user_states')
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profiles_user_id'))

    op.drop_table('user_profiles')
    # ### end Alembic commands ###