"""Feedback-loop acceptance tests (TEST3 / TEST4 / TEST5)."""

from __future__ import annotations

from datetime import date

from fastapi.testclient import TestClient

from app.ml.base import AdjustmentRoute, AdjustmentSeverity
from tests.agent.conftest import override_plan_service, preview_of


def _create_plan(client: TestClient, headers: dict, payload: dict) -> int:
    body = preview_of(client, headers, payload)
    confirmed = client.post(
        f"/api/v1/plans/preview/{body['thread_id']}/confirm", headers=headers
    )
    assert confirmed.status_code == 201, confirmed.text
    return confirmed.json()["plan"]["id"]


def _submit_feedback(client: TestClient, headers: dict, plan_id: int, rate: float) -> dict:
    response = client.post(
        f"/api/v1/plans/{plan_id}/feedback",
        json={"date": date.today().isoformat(), "completion_rate": rate},
        headers=headers,
    )
    assert response.status_code == 201, response.text
    return response.json()


def test_feedback_no_change_keeps_plan(
    client: TestClient, auth_headers: dict, preview_payload: dict
) -> None:
    """TEST 3: NO_CHANGE -> no LLM, no new plan version."""
    override_plan_service(client, route=AdjustmentRoute.NO_CHANGE)
    plan_id = _create_plan(client, auth_headers, preview_payload)

    body = _submit_feedback(client, auth_headers, plan_id, 0.9)

    assert body["adjustment"]["route"] == "NO_CHANGE"
    assert body["adjustment"]["new_plan_id"] is None
    assert body["replan_triggered"] is False
    # The plan is untouched.
    plan = client.get(f"/api/v1/plans/{plan_id}", headers=auth_headers).json()
    assert plan["version"] == 1
    assert plan["status"] == "active"


def test_feedback_micro_adjust_creates_light_version(
    client: TestClient, auth_headers: dict, preview_payload: dict
) -> None:
    """TEST 4: MICRO_ADJUST -> scheduler + rules, no LLM replan."""
    override_plan_service(
        client,
        route=AdjustmentRoute.MICRO_ADJUST,
        severity=AdjustmentSeverity.MEDIUM,
    )
    plan_id = _create_plan(client, auth_headers, preview_payload)

    body = _submit_feedback(client, auth_headers, plan_id, 0.7)
    new_plan_id = body["adjustment"]["new_plan_id"]

    assert body["adjustment"]["route"] == "MICRO_ADJUST"
    assert new_plan_id is not None
    assert new_plan_id != plan_id

    new_plan = client.get(f"/api/v1/plans/{new_plan_id}", headers=auth_headers).json()
    old_plan = client.get(f"/api/v1/plans/{plan_id}", headers=auth_headers).json()
    assert new_plan["version"] == 2
    assert new_plan["parent_plan_id"] == plan_id
    assert old_plan["status"] == "superseded"
    # Deterministic path: tasks are re-placed, not regenerated by an LLM.
    assert new_plan["tasks"]


def test_feedback_full_replan_creates_v2(
    client: TestClient, auth_headers: dict, preview_payload: dict
) -> None:
    """TEST 5: FULL_REPLAN -> context + LLM -> new plan version."""
    override_plan_service(
        client,
        route=AdjustmentRoute.FULL_REPLAN,
        severity=AdjustmentSeverity.HIGH,
    )
    plan_id = _create_plan(client, auth_headers, preview_payload)

    body = _submit_feedback(client, auth_headers, plan_id, 0.2)
    new_plan_id = body["adjustment"]["new_plan_id"]

    assert body["adjustment"]["route"] == "FULL_REPLAN"
    assert body["adjustment"]["degraded"] is False
    assert new_plan_id is not None

    new_plan = client.get(f"/api/v1/plans/{new_plan_id}", headers=auth_headers).json()
    assert new_plan["version"] == 2
    assert new_plan["parent_plan_id"] == plan_id
    assert len(new_plan["tasks"]) == 2
    # Goal linkage survives the rebuild (regression guard).
    assert len(new_plan["goals"]) == 2


def test_feedback_includes_agent_adjustment_payload(
    client: TestClient, auth_headers: dict, preview_payload: dict
) -> None:
    override_plan_service(client, route=AdjustmentRoute.NO_CHANGE)
    plan_id = _create_plan(client, auth_headers, preview_payload)
    body = _submit_feedback(client, auth_headers, plan_id, 0.9)

    adjustment = body["adjustment"]
    assert adjustment["source"]
    assert adjustment["reasons"]
